TRANSLATIONS = {
    "window_title": "Add Audio and Subtitles",
    "series_folder": "Series Folder:",
    "output_folder": "Output Folder:",
    "browse_button": "Browse...",
    "audio_tracks": "Audio Tracks",
    "add_audio": "Add Audio",
    "subtitles": "Subtitles",
    "add_subtitles": "Add Subtitles",
    "start_processing": "Start Processing",
    "path_placeholder": "File path",
    "language_label": "Language:",
    "language_placeholder": "ru/en etc",
    "track_name_label": "Name:",
    "track_name_placeholder": "Track name",
    "remove_button": "−",
    "invalid_series_folder": "Invalid series folder",
    "invalid_output_folder": "Invalid output folder",
    "missing_language": "Missing language in {widget}",
    "preparing_processing": "Preparing for processing...",
    "processing_status": "Processing...",
    "critical_error": "Critical error: {error}",
    "select_directory": "Select directory",
    "drag_and_drop_placeholder": "Drag and drop folders here",
    "drop_here": "Drop here",
}