TRANSLATIONS = {
    "window_title": "Добавление аудио и субтитров",
    "series_folder": "Папка сериала:",
    "output_folder": "Выходная папка:",
    "browse_button": "Обзор...",
    "audio_tracks": "Аудио дорожки",
    "add_audio": "Добавить аудио",
    "subtitles": "Субтитры",
    "add_subtitles": "Добавить субтитры",
    "start_processing": "Начать обработку",
    "path_placeholder": "Путь к файлам",
    "language_label": "Язык:",
    "language_placeholder": "ru/en и т.п.",
    "track_name_label": "Название:",
    "track_name_placeholder": "Название дорожки",
    "remove_button": "−",
    "invalid_series_folder": "Неверная папка сериала",
    "invalid_output_folder": "Неверная выходная папка",
    "missing_language": "Не указан язык в {widget}",
    "preparing_processing": "Подготовка к обработке...",
    "processing_status": "Обработка...",
    "critical_error": "Критическая ошибка: {error}",
    "select_directory": "Выберите папку"
}